(function(){
'use strict';
const BUILTINS=[
 {id:'classic',name:'经典白',bg:'#ffffff',border:'#dfe3eb',color:'#2c3140',radius:12,shadow:'0 2px 8px #17203314'},
 {id:'ocean',name:'海洋蓝',bg:'#eaf4ff',border:'#4d93e6',color:'#174f8f',radius:14,shadow:'0 5px 14px #2f77c52b'},
 {id:'mint',name:'薄荷绿',bg:'#eafff6',border:'#37b77b',color:'#176644',radius:18,shadow:'0 5px 14px #229a6622'},
 {id:'sunset',name:'日落橙',bg:'#fff3e9',border:'#ee8c45',color:'#8c431b',radius:10,shadow:'0 5px 14px #d26b2b25'},
 {id:'ink',name:'墨黑标题',bg:'#252a34',border:'#11151c',color:'#ffffff',radius:7,shadow:'0 7px 16px #1115',fontWeight:700},
 {id:'note',name:'便签纸',bg:'#fff9b8',border:'#e7d86a',color:'#5b5120',radius:2,shadow:'3px 5px 10px #6f63352c'},
 {id:'glass',name:'玻璃紫',bg:'#f1edffdd',border:'#9273e8',color:'#4a318c',radius:20,shadow:'0 8px 22px #6746b833'},
 {id:'outline',name:'极简线框',bg:'transparent',border:'#5c6475',color:'#303644',radius:0,shadow:'none',borderWidth:2},
 {id:'neon',name:'霓虹夜色',bg:'#17162b',border:'#52e4ff',color:'#f1fbff',radius:12,shadow:'0 0 13px #42dff077'}
];
let customStyles=[],styleSettings={},styles=BUILTINS.map(x=>Object.assign({_builtin:true,scope:'all'},x)),defaultStyleId='classic',placementMode='normal',currentTab='styles',externalPath='',systemFontFamilies=['system-ui','sans-serif','serif','monospace'];
const q=s=>document.querySelector(s), ids=()=>[...selSet].filter(id=>TB[id]&&!TB[id]._ghost);
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
function safeImageData(value){const s=String(value||'');if(s.length>36000000)return'';const prefix=/^data:image\/(?:png|jpeg|gif|bmp);base64,/i.exec(s);return prefix&&/^[A-Za-z0-9+/=]+$/.test(s.slice(prefix[0].length))?s:'';}
function getStyle(id){return styles.find(x=>x.id===id)||BUILTINS[0];}
function styleData(t){const base=getStyle(t.textStyleId||defaultStyleId||'classic');return Object.assign({},base,t.textStyle||{});}
function effectiveRules(t){const inherited=styleData(t).textRules||{},own=t.textRules||{};return t._textRulesOverride===true||!Object.keys(inherited).length?Object.assign({},inherited,own):Object.assign({},inherited);}
function effectiveSizing(t){const inherited=styleData(t).textSizing||{},own=t.textSizing||{};return t._textSizingOverride===true||!Object.keys(inherited).length?Object.assign({},inherited,own):Object.assign({},inherited);}
function sizingMode(mode){return mode==='stretch'?'stretch':'uniform';}
function oneCharacterRegion(s,f){const fontSize=Math.max(1,Number(f&&f.fontSize||s&&s.fontSize)||14),lineHeight=Math.max(.8,Number(f&&f.lineHeight)||1.4);return{width:fontSize+12,height:fontSize*lineHeight+8};}
function textRegionBaseline(s,z,mode,aspect,glyph){const tr=s&&s.textRegion||{},wf=Number(tr.w)>0?Math.min(1,Math.max(.001,Number(tr.w)/100)):1,hf=Number(tr.h)>0?Math.min(1,Math.max(.001,Number(tr.h)/100)):1,targetW=Math.max(1,Number(glyph&&glyph.width)||26),targetH=Math.max(1,Number(glyph&&glyph.height)||27.6);aspect=Math.max(.1,Number(aspect)||1.8);
 // Both policies start from the authored frame ratio.  Free stretch is allowed to
 // change the axes independently only after this one-character baseline; deriving
 // width and height separately from the region fractions turns wide artwork into a
 // vertical frame before the user has typed anything.
 let width=Math.max(targetW/wf,targetH*aspect/hf),height=width/aspect;
 const scale=Math.min(1,10000/Math.max(1,width),10000/Math.max(1,height));return{width:width*scale,height:height*scale,targetW,targetH,wf,hf};}
function setVar(el,k,v){if(v==null||v==='')el.style.removeProperty(k);else el.style.setProperty(k,String(v));}
async function loadSystemFonts(){if(typeof window.queryLocalFonts!=='function')return;try{const fonts=await window.queryLocalFonts(),names=[...new Set(fonts.map(x=>x.family).filter(Boolean))].sort((a,b)=>a.localeCompare(b));if(names.length){systemFontFamilies=names;if(q('#textStylePanel')&&currentTab==='font')refresh();}}catch(_){}}
function fontOptions(current){const names=systemFontFamilies.includes(current)?systemFontFamilies:[current,...systemFontFamilies].filter(Boolean);return names.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');}
function styleBounds(s){const parts=[];(Array.isArray(s.layers)?s.layers:[]).forEach(l=>{if(l.isVisible===false)return;const x=Number(l.x)||0,y=Number(l.y)||0,w=Math.max(0,Number(l.w)||0),h=Math.max(0,Number(l.h)||0),a=(Number(l.rotation)||0)*Math.PI/180,cx=x+w/2,cy=y+h/2;if(Math.abs(a)<.0001){parts.push({x,y,w,h});return;}const pts=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]].map(p=>{const dx=p[0]-cx,dy=p[1]-cy;return [cx+dx*Math.cos(a)-dy*Math.sin(a),cy+dx*Math.sin(a)+dy*Math.cos(a)];});const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);parts.push({x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)});});const tr=s.textRegion;if(tr&&Number(tr.w)>0&&Number(tr.h)>0)parts.push({x:Number(tr.x)||0,y:Number(tr.y)||0,w:Number(tr.w),h:Number(tr.h)});if(!parts.length)return{x:0,y:0,w:100,h:100};const x=Math.min(...parts.map(p=>p.x)),y=Math.min(...parts.map(p=>p.y)),r=Math.max(...parts.map(p=>p.x+p.w)),b=Math.max(...parts.map(p=>p.y+p.h));return{x,y,w:Math.max(.01,r-x),h:Math.max(.01,b-y)};}
// The editor stores every X/W value as a percentage of its 900px design width and
// every Y/H value as a percentage of its 520px design height.  Its preview always
// renders that complete 0..100 by 0..100 design plane.  Cropping the SVG to the
// visible layers changes both the artwork scale and the text-region position, so
// keep the same fixed coordinate plane here as well.
function renderBounds(){return{x:0,y:0,w:100,h:100};}
function renderArt(card,s){
 const NS='http://www.w3.org/2000/svg',node=card.closest('.node'),inner=node&&node._inner;
 let svg=card.querySelector(':scope > .ts-decoration');
 if(svg&&svg.tagName.toLowerCase()!=='svg'){svg.remove();svg=null;}
 if(!svg){svg=document.createElementNS(NS,'svg');svg.classList.add('ts-decoration');svg.setAttribute('preserveAspectRatio','none');card.prepend(svg);}
 let defsEl=svg.querySelector(':scope > defs.ts-defs'),artEl=svg.querySelector(':scope > g.ts-artwork');
 if(!defsEl){defsEl=document.createElementNS(NS,'defs');defsEl.classList.add('ts-defs');svg.prepend(defsEl);}
 if(!artEl){artEl=document.createElementNS(NS,'g');artEl.classList.add('ts-artwork');defsEl.after(artEl);}
 const pixelW=Math.max(1,card.clientWidth||card.getBoundingClientRect().width||100),pixelH=Math.max(1,card.clientHeight||card.getBoundingClientRect().height||100),sx=pixelW/100,sy=pixelH/100;
 svg.setAttribute('viewBox',`0 0 ${pixelW} ${pixelH}`);
 const tr=s&&s.textRegion||{},useComposite=!!(node&&node.classList.contains('ts-replace-frame')&&node.classList.contains('ts-has-text-region')&&inner),rx=Number(tr.x)||0,ry=Number(tr.y)||0,rw=Math.max(0,Number(tr.w)||0),rh=Math.max(0,Number(tr.h)||0);
 let textObject=svg.querySelector(':scope > foreignObject.ts-text-object');
 if(useComposite){
  if(!textObject){textObject=document.createElementNS(NS,'foreignObject');textObject.classList.add('ts-text-object');svg.appendChild(textObject);}
  textObject.setAttribute('x',rx*sx);textObject.setAttribute('y',ry*sy);textObject.setAttribute('width',rw*sx);textObject.setAttribute('height',rh*sy);
  if(inner.parentNode!==textObject)textObject.appendChild(inner);
  svg.classList.add('ts-composite');
  setVar(node,'--ts-group-anchor-x',(rx+rw/2)+'%');setVar(node,'--ts-group-anchor-y',(ry+rh/2)+'%');
 }else{
  if(textObject&&inner&&inner.parentNode===textObject)card.insertBefore(inner,card.querySelector('.tag-row'));
  if(textObject)textObject.remove();
  svg.classList.remove('ts-composite');
 }
 const layers=Array.isArray(s.layers)?s.layers:[],uid='tsa-'+String(node&&node.dataset.id||Math.random()).replace(/[^a-z0-9_-]/gi,'-'),maskRect=`x="0" y="0" width="${pixelW}" height="${pixelH}"`;
 const geom=(l,paint=true,color='')=>{
  const type=['rect','ellipse','line','image'].includes(l.type)?l.type:'rect',x=(Number(l.x)||0)*sx,y=(Number(l.y)||0)*sy,w=(Number(l.w)||0)*sx,h=(Number(l.h)||0)*sy,rot=Number(l.rotation)||0,cx=x+w/2,cy=y+h/2,transform=rot?` transform="rotate(${rot} ${cx} ${cy})"`:'',radius=Math.max(0,Number(l.radius)||0),round=radius?` rx="${Math.min(Math.abs(w)/2,radius)}" ry="${Math.min(Math.abs(h)/2,radius)}"`:'';
  if(!paint){if(type==='ellipse')return `<ellipse cx="${cx}" cy="${cy}" rx="${w/2}" ry="${h/2}"${transform} fill="${color||'#fff'}"/>`;if(type==='line')return `<line x1="${x}" y1="${y}" x2="${x+w}" y2="${y+h}"${transform} stroke="${color||'#fff'}" stroke-width="${Math.max(1,Number(l.strokeWidth)||1)}"/>`;return `<rect x="${x}" y="${y}" width="${w}" height="${h}"${round}${transform} fill="${color||'#fff'}"/>`;}
  const opacity=l.opacity==null?1:Number(l.opacity);if(type==='image'){const href=safeImageData(l.imageData);return href?`<image x="${x}" y="${y}" width="${w}" height="${h}" href="${esc(href)}" preserveAspectRatio="none"${transform} opacity="${opacity}"/>`:'';}const fill=type==='line'?'none':esc(l.fill||'#DDE9FF'),stroke=esc(l.stroke||'#5B8DEF'),sw=Math.max(0,Number(l.strokeWidth)||0),common=`${transform} fill="${fill}" stroke="${stroke}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke" opacity="${opacity}"`;if(type==='ellipse')return `<ellipse cx="${cx}" cy="${cy}" rx="${w/2}" ry="${h/2}" ${common}/>`;if(type==='line')return `<line x1="${x}" y1="${y}" x2="${x+w}" y2="${y+h}" ${common}/>`;return `<rect x="${x}" y="${y}" width="${w}" height="${h}"${round} ${common}/>`;
 };
 let defs='',body='';layers.forEach((l,i)=>{if(l.isVisible===false)return;const ownEffect=i>0&&((l.clipMode&&l.clipMode!=='none')||(l.maskMode&&l.maskMode!=='none'));if(ownEffect)return;const cutter=layers[i+1]&&layers[i+1].isVisible!==false?layers[i+1]:null;let effect='';if(cutter&&cutter.maskMode&&cutter.maskMode!=='none'){const mid=`${uid}-usermask-${i}`,inverse=cutter.maskMode==='inverseAlpha'||cutter.maskMode==='inverseLuminance',lum=cutter.maskMode==='luminance'||cutter.maskMode==='inverseLuminance',source=lum&&!inverse?geom(cutter):geom(cutter,false,inverse?'#000':'#fff');defs+=`<mask id="${mid}" maskUnits="userSpaceOnUse" mask-type="luminance" ${maskRect}><rect ${maskRect} fill="${inverse?'#fff':'#000'}"/>${source}</mask>`;effect=` mask="url(#${mid})"`;}else if(cutter&&cutter.clipMode==='intersect'){const cid=`${uid}-clip-${i}`;defs+=`<clipPath id="${cid}" clipPathUnits="userSpaceOnUse">${geom(cutter,false,'#fff')}</clipPath>`;effect=` clip-path="url(#${cid})"`;}else if(cutter&&cutter.clipMode==='subtract'){const mid=`${uid}-mask-${i}`;defs+=`<mask id="${mid}" maskUnits="userSpaceOnUse" mask-type="luminance" ${maskRect}><rect ${maskRect} fill="#fff"/>${geom(cutter,false,'#000')}</mask>`;effect=` mask="url(#${mid})"`;}body+=`<g${effect}>${geom(l)}</g>`;});
 defsEl.innerHTML=defs;artEl.innerHTML=body;
}
let textMeasureCanvas;
function textDemand(inner,text){try{const cs=getComputedStyle(inner),canvas=textMeasureCanvas||(textMeasureCanvas=document.createElement('canvas')),ctx=canvas.getContext('2d');ctx.font=`${cs.fontStyle} ${cs.fontWeight} ${cs.fontSize} ${cs.fontFamily}`;const fs=Math.max(1,parseFloat(cs.fontSize)||14),lh=Math.max(fs,parseFloat(cs.lineHeight)||fs*1.4),spacing=parseFloat(cs.letterSpacing)||0,lines=String(text).split('\n'),widths=lines.map(line=>{const chars=Array.from(line),raw=ctx.measureText(line||' ').width+Math.max(0,chars.length-1)*spacing;return Math.max(fs*.45,raw);});return{fontSize:fs,lineHeight:lh,widths,longest:Math.max(fs*.45,...widths),explicitLines:Math.max(1,lines.length),characters:Math.max(1,Array.from(String(text).replace(/\n/g,'')).length)};}catch(_){const characters=Math.max(1,Array.from(String(text).replace(/\n/g,'')).length);return{fontSize:14,lineHeight:19.6,widths:[characters*14],longest:characters*14,explicitLines:1,characters};}}
function measuredTextBox(demand,regionWidth,wrap,safe=false){const padX=12+(safe?6:0),contentWidth=Math.max(1,regionWidth-padX);let rows=0;for(const lineWidth of demand.widths)rows+=wrap?Math.max(1,Math.ceil((lineWidth-.01)/contentWidth)):1;return{width:(wrap?Math.min(demand.longest,contentWidth):demand.longest)+padX,height:rows*demand.lineHeight+8+(safe&&rows>1?demand.lineHeight:0)};}
function overflowRatios(inner){inner.classList.add('ts-measuring');const cw=Math.max(1,inner.clientWidth),ch=Math.max(1,inner.clientHeight);let rw=1,rh=1;try{const range=document.createRange();range.selectNodeContents(inner);const r=range.getBoundingClientRect(),cs=getComputedStyle(inner),px=(parseFloat(cs.paddingLeft)||0)+(parseFloat(cs.paddingRight)||0),py=(parseFloat(cs.paddingTop)||0)+(parseFloat(cs.paddingBottom)||0);rw=Math.max(1,(r.width+px)/cw);rh=Math.max(1,(r.height+py)/ch);}catch(_){rw=Math.max(1,inner.scrollWidth)/cw;rh=Math.max(1,inner.scrollHeight)/ch;}inner.classList.remove('ts-measuring');return{cw,ch,rw,rh};}
function preserveTextRegionAnchor(t,previous,width,height){if(!previous||!previous.positioned||t.parentBrace||t._nodeAttach||!Array.isArray(roots)||!roots.includes(t.id))return;const ax=Number.isFinite(t._textRegionAnchorX)?t._textRegionAnchorX:.5,ay=Number.isFinite(t._textRegionAnchorY)?t._textRegionAnchorY:.5,anchorX=t._x+previous.w*ax,anchorY=t._cy+previous.h*(ay-.5);t.x=anchorX-width*ax;t.y=anchorY-height*(ay-.5);}
function fitTextRegion(e,t,s,mode,aspect,previous){const card=e._card,inner=e._inner,z=effectiveSizing(t),f=t.textFormat||{},editingNow=inner.getAttribute('contenteditable')==='true',text=editingNow?(inner.textContent||''):(t.text||'');mode=sizingMode(mode);aspect=Math.max(.1,Number(aspect)||1.8);const baseline=textRegionBaseline(s,z,mode,aspect,oneCharacterRegion(s,f));let width=baseline.width,height=baseline.height;
 const apply=()=>{width=Math.max(1,Math.min(10000,width));height=Math.max(1,Math.min(10000,height));if(mode==='uniform'){height=width/aspect;setVar(e,'--ts-uniform-size',width+'px');setVar(e,'--ts-uniform-height',height+'px');}else{setVar(e,'--ts-stretch-width',width+'px');setVar(e,'--ts-stretch-height',height+'px');}void card.offsetWidth;renderArt(card,s);};
 if(text.length){const demand=textDemand(inner,text),wrap=f.wrap!==false,baseRegionWidth=baseline.width*baseline.wf,baseRegionHeight=baseline.height*baseline.hf,fits=(s,safe=false)=>{const box=measuredTextBox(demand,baseRegionWidth*s,wrap,safe);return box.width<=baseRegionWidth*s+.5&&box.height<=baseRegionHeight*s+.5;};if(mode==='uniform'){if(!fits(1)){let low=1,high=1;while(high<10000/Math.max(baseline.width,baseline.height)&&!fits(high,true))high*=2;high=Math.min(high,10000/Math.max(baseline.width,baseline.height));for(let i=0;i<36;i++){const middle=(low+high)/2;if(fits(middle,true))high=middle;else low=middle;}width=baseline.width*high;height=width/aspect;}}else{const initial=measuredTextBox(demand,baseRegionWidth,wrap);if(initial.width>baseRegionWidth+.5||initial.height>baseRegionHeight+.5){const naturalRegionWidth=demand.longest+18,desiredRegionWidth=Math.max(baseRegionWidth,wrap?Math.min(420,naturalRegionWidth):naturalRegionWidth),box=measuredTextBox(demand,desiredRegionWidth,wrap,true);width=desiredRegionWidth/baseline.wf;height=Math.max(baseline.height,box.height/baseline.hf);}}}
 apply();
 if(text.length)for(let i=0;i<4;i++){const cw=Math.max(1,inner.clientWidth),ch=Math.max(1,inner.clientHeight),dx=Math.max(0,inner.scrollWidth-cw),dy=Math.max(0,inner.scrollHeight-ch);if(dx<=1&&dy<=1)break;if(mode==='uniform'){const correction=Math.max(1,(cw+dx+2)/cw,(ch+dy+2)/ch);width=Math.min(10000,width*correction);height=width/aspect;}else{width=Math.min(10000,width+(dx>1?(dx+2)/baseline.wf:0));height=Math.min(10000,height+(dy>1?(dy+2)/baseline.hf:0));}apply();}
 const fittedWidth=Math.max(1,card.offsetWidth||width),fittedHeight=Math.max(1,card.offsetHeight||height);preserveTextRegionAnchor(t,previous,fittedWidth,fittedHeight);if(!text.length)delete e._tsFit;else e._tsFit={length:Array.from(text).length,width:fittedWidth,height:fittedHeight,mode};}
window.applyTextStyleToNode=function(id){
 const t=TB[id],e=els[id];if(!t||!e)return;const s=styleData(t),f=t.textFormat||{},z=effectiveSizing(t),layers=Array.isArray(s.layers)?s.layers:[],replace=!!s.replaceFrame&&layers.length>0,tr=s.textRegion,hasRegion=!!(tr&&tr.w>0&&tr.h>0),bounds=renderBounds(s),rawMode=z.mode||s.textSizing&&s.textSizing.mode||'',effectiveMode=(rawMode||replace)?sizingMode(rawMode):'';e.classList.toggle('ts-custom',!!(t.textStyleId||t.textStyle));e.classList.toggle('ts-replace-frame',replace);e.classList.toggle('ts-has-text-region',replace&&hasRegion);e.classList.remove('ts-size-fixed','ts-size-uniform','ts-size-stretch');if(effectiveMode)e.classList.add('ts-size-'+effectiveMode);
 const card=e._card,previous={w:Math.max(1,Number(t._w)||card.offsetWidth||1),h:Math.max(1,Number(t._h)||card.offsetHeight||1),positioned:Number.isFinite(t._x)&&Number.isFinite(t._cy)};if(replace){card.style.setProperty('background','transparent','important');card.style.setProperty('background-color','transparent','important');card.style.setProperty('border-width','0px','important');card.style.setProperty('box-shadow','none','important');}else{card.style.removeProperty('background');card.style.removeProperty('background-color');card.style.removeProperty('border-width');card.style.removeProperty('box-shadow');}
 setVar(e,'--ts-bg',replace?'transparent':s.bg);setVar(e,'--ts-border',replace?'transparent':s.border);setVar(e,'--ts-color',f.color||s.color);setVar(e,'--ts-radius',replace?'0px':(s.radius==null?12:s.radius)+'px');setVar(e,'--ts-shadow',replace?'none':s.shadow||'none');setVar(e,'--ts-border-width',replace?'0px':(s.borderWidth||1.5)+'px');setVar(e,'--ts-font-family',f.fontFamily||s.fontFamily||'inherit');setVar(e,'--ts-font-size',(f.fontSize||s.fontSize||14)+'px');setVar(e,'--ts-font-weight',f.bold?700:(s.fontWeight||400));setVar(e,'--ts-font-style',f.italic?'italic':'normal');setVar(e,'--ts-decoration',f.underline?'underline':'none');
 const textAlign=f.align||s.textAlign||(hasRegion?'center':'left');setVar(e,'--ts-align',textAlign);setVar(e,'--ts-letter-spacing',(f.letterSpacing||0)+'px');setVar(e,'--ts-line-height',f.lineHeight||1.4);setVar(e,'--ts-white-space',f.wrap===false?'nowrap':'pre-wrap');setVar(e,'--ts-max-width','none');setVar(e,'--ts-padding',s.padding||'11px 18px');
 const designAspect=9/5.2,storedAspect=Number(z.aspect||(s.textSizing&&s.textSizing.aspect)),aspect=rawMode==='auto'?designAspect:(storedAspect>0?storedAspect:designAspect),glyph=oneCharacterRegion(s,f),uniformBase=textRegionBaseline(s,z,'uniform',aspect,glyph),stretchBase=textRegionBaseline(s,z,'stretch',aspect,glyph);
 setVar(e,'--ts-fixed-width',stretchBase.width+'px');setVar(e,'--ts-fixed-height',stretchBase.height+'px');setVar(e,'--ts-aspect',aspect);setVar(e,'--ts-uniform-size',uniformBase.width+'px');setVar(e,'--ts-uniform-height',uniformBase.height+'px');setVar(e,'--ts-stretch-width',stretchBase.width+'px');setVar(e,'--ts-stretch-height',stretchBase.height+'px');setVar(e,'--ts-min-height',(z.minHeight||48)+'px');
 if(hasRegion){const rx=Number(tr.x)||0,ry=Number(tr.y)||0,rw=Math.max(0,Number(tr.w)||0),rh=Math.max(0,Number(tr.h)||0);setVar(e,'--ts-text-x',rx+'%');setVar(e,'--ts-text-y',ry+'%');setVar(e,'--ts-text-w',rw+'%');setVar(e,'--ts-text-h',rh+'%');setVar(e,'--ts-text-justify',textAlign==='left'?'flex-start':textAlign==='right'?'flex-end':'center');t._textRegionAnchorX=Math.min(1,Math.max(0,(rx+rw/2)/100));t._textRegionAnchorY=Math.min(1,Math.max(0,(ry+rh/2)/100));}else{delete t._textRegionAnchorX;delete t._textRegionAnchorY;}renderArt(card,s);if(replace&&hasRegion)fitTextRegion(e,t,s,effectiveMode,aspect,previous);
};
function applyAll(){Object.keys(TB).forEach(window.applyTextStyleToNode);layout();}
function shell(){if(q('#textStylePanel'))return;document.body.insertAdjacentHTML('beforeend',`<aside id="textStylePanel"><div class="ts-head"><strong>文本框样式与字体</strong><span class="sp"></span><button class="ts-close" title="关闭">×</button></div><div class="ts-tabs"><button class="ts-tab on" data-tab="styles">样式库</button><button class="ts-tab" data-tab="font">字体</button><button class="ts-tab" data-tab="rules">尺寸与输入</button></div><div class="ts-body"><section class="ts-page on" data-page="styles"><div class="ts-grid"></div></section><section class="ts-page" data-page="font"></section><section class="ts-page" data-page="rules"></section></div><div class="ts-status">请选择文本框</div></aside><div class="ts-card-menu" hidden></div>`);q('.ts-close').onclick=close;q('.ts-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;currentTab=b.dataset.tab;refresh();};}
function open(tab,mode='normal'){shell();placementMode=mode;currentTab=tab||'styles';refresh();document.body.classList.add('ts-panel-open');q('#textStylePanel').style.display='flex';setTimeout(()=>{if(typeof layout==='function')layout();},0);}
function close(){document.body.classList.remove('ts-panel-open');q('#textStylePanel').style.display='none';closeStyleMenu();setTimeout(()=>{if(typeof layout==='function')layout();},0);}
function selected(){const a=ids();return a.length?a:[selPrimary()].filter(Boolean);}
function patch(part,key,value){const a=selected();if(!a.length)return;a.forEach(id=>{const inherited=part==='textRules'?effectiveRules(TB[id]):part==='textSizing'?effectiveSizing(TB[id]):TB[id][part]||{},next=Object.assign({},inherited,{[key]:value});if(part==='textSizing')next.mode=sizingMode(next.mode);TB[id][part]=next;if(part==='textRules')TB[id]._textRulesOverride=true;if(part==='textSizing')TB[id]._textSizingOverride=true;render([id]);});layout();markDirty();}
async function persistStyles(){const lib={format:'thoughtcanvas-text-styles',version:1,defaultStyleId,styleSettings,styles:customStyles.map(x=>{const y=Object.assign({},x);delete y._builtin;return y;})};try{let r;if(window.api&&api.saveTextStyles)r=await api.saveTextStyles(lib);else{localStorage.setItem('bmap.textStyles',JSON.stringify(lib));r={ok:true,path:'localStorage'};}if(!r||r.ok===false)throw new Error(r&&r.error||'保存失败');externalPath=r.path||externalPath;q('.ts-status').textContent='样式库已永久保存';}catch(e){q('.ts-status').textContent='样式库保存失败：'+e.message;} }
function closeStyleMenu(){const m=q('.ts-card-menu');if(m)m.hidden=true;}
function rebuildStyles(){styles=BUILTINS.map(x=>Object.assign({_builtin:true,scope:(styleSettings[x.id]&&styleSettings[x.id].scope)||'all'},x)).concat(customStyles.map(x=>Object.assign({_builtin:false,scope:(styleSettings[x.id]&&styleSettings[x.id].scope)||x.scope||'all'},x)));}
function setStyleScope(id,scope){styleSettings[id]=Object.assign({},styleSettings[id]||{},{scope});const s=customStyles.find(x=>x.id===id);if(s)s.scope=scope;rebuildStyles();persistStyles();refresh();}
function deleteStyle(id){const i=customStyles.findIndex(x=>x.id===id);if(i<0)return;customStyles.splice(i,1);if(defaultStyleId===id)defaultStyleId='classic';Object.values(TB).forEach(t=>{if(t.textStyleId===id)t.textStyleId=defaultStyleId;});rebuildStyles();persistStyles();applyAll();refresh();}
function setDefault(id){defaultStyleId=id;persistStyles();refresh();}
function applyStyleRecord(t,style,placement='normal'){delete t.textStyle;t.textStyleId=style.id;t.textStylePlacement=placement;delete t.textRules;delete t.textSizing;delete t._textRulesOverride;delete t._textSizingOverride;}
function applyStyleToAll(style){Object.values(TB).forEach(t=>{if(t&&!t._ghost)applyStyleRecord(t,style,t._nodeAttach?'node':'normal');});render();layout();markDirty();refresh();}
function placeStyleOnAllNodes(style){if(typeof window.placeTextStyleOnAllStructuralNodes!=='function')return;const count=window.placeTextStyleOnAllStructuralNodes(style.id);q('.ts-status').textContent=`已在 ${count} 个节点上放置此样式文本框`;refresh();}
function openStyleMenu(style,x,y){const m=q('.ts-card-menu');m.innerHTML=`<button data-a="default">设为默认文本框样式</button><button data-a="apply-all">应用于所有文本框</button><button data-a="place-nodes">在所有节点上放置此样式文本框</button><button data-a="delete" class="danger" ${style._builtin?'disabled':''}>删除自定义样式${style._builtin?'（内置不可删除）':''}</button>`;m.hidden=false;m.style.left=Math.min(x,innerWidth-260)+'px';m.style.top=Math.min(y,innerHeight-190)+'px';m.onclick=e=>{const a=e.target.closest('button:not(:disabled)')?.dataset.a;if(!a)return;closeStyleMenu();if(a==='default')setDefault(style.id);else if(a==='apply-all')applyStyleToAll(style);else if(a==='place-nodes')placeStyleOnAllNodes(style);else if(a==='delete')deleteStyle(style.id);};}
function refresh(){shell();q('.ts-tabs').querySelectorAll('.ts-tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===currentTab));q('.ts-body').querySelectorAll('.ts-page').forEach(x=>x.classList.toggle('on',x.dataset.page===currentTab));const a=selected(),t=a.length?TB[a[0]]:{};
 if(currentTab==='styles'){
  q('.ts-grid').innerHTML=styles.map(s=>`<button class="ts-card ${t&&t.textStyleId===s.id?'on':''} ${defaultStyleId===s.id?'default':''}" data-id="${esc(s.id)}"><span class="ts-sample" style="background:${s.replaceFrame?'transparent':esc(s.bg)};border-color:${s.replaceFrame?'transparent':esc(s.border)};color:${esc(s.color)};border-radius:${Number(s.radius)||0}px;box-shadow:${s.replaceFrame?'none':esc(s.shadow||'none')};font-family:${esc(s.fontFamily||'inherit')};font-weight:${s.fontWeight||400}">示例文字</span><span class="ts-name">${esc(s.name)}</span><span class="ts-scope">${s._builtin?'内置样式':'自定义样式'}</span></button>`).join('');
  q('.ts-grid').querySelectorAll('.ts-card').forEach(b=>{const s=getStyle(b.dataset.id);if(s.layers&&s.layers.length)renderArt(b.querySelector('.ts-sample'),s);});
  q('.ts-grid').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;const a=selected();if(!a.length){q('.ts-status').textContent='请先选中一个或多个文本框';return;}const preset=getStyle(b.dataset.id);a.forEach(id=>{applyStyleRecord(TB[id],preset,TB[id]._nodeAttach?'node':placementMode);render([id]);});layout();markDirty();refresh();};
  q('.ts-grid').oncontextmenu=e=>{const b=e.target.closest('[data-id]');if(!b)return;e.preventDefault();e.stopPropagation();openStyleMenu(getStyle(b.dataset.id),e.clientX,e.clientY);};
 }
 if(currentTab==='font'){const f=t.textFormat||{},currentFont=f.fontFamily||'system-ui';q('[data-page="font"]').innerHTML=`<div class="ts-section"><h4>选中文本框的字体</h4><label class="ts-row"><span>字体</span><select data-f="fontFamily">${fontOptions(currentFont)}</select></label><label class="ts-row"><span>字号</span><input data-f="fontSize" type="number" min="8" max="96" value="${f.fontSize||14}"></label><label class="ts-row"><span>文字颜色</span><input data-f="color" type="color" value="${esc(f.color||'#2c3140')}"></label><label class="ts-row"><span>对齐</span><select data-f="align"><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label><label class="ts-row"><span>字间距</span><input data-f="letterSpacing" type="number" min="-2" max="20" step="0.5" value="${f.letterSpacing||0}"></label><label class="ts-row"><span>行高</span><input data-f="lineHeight" type="number" min="0.8" max="3" step="0.1" value="${f.lineHeight||1.4}"></label><div class="ts-checks"><label><input data-f="bold" type="checkbox" ${f.bold?'checked':''}> 粗体</label><label><input data-f="italic" type="checkbox" ${f.italic?'checked':''}> 斜体</label><label><input data-f="underline" type="checkbox" ${f.underline?'checked':''}> 下划线</label><label><input data-f="wrap" type="checkbox" ${f.wrap!==false?'checked':''}> 自动换行</label></div><p class="ts-hint">字体列表来自当前 Windows 系统，不随应用打包字体文件。</p></div>`;const page=q('[data-page="font"]');page.querySelector('[data-f="fontFamily"]').value=currentFont;page.querySelector('[data-f="align"]').value=f.align||'left';page.onchange=e=>{const el=e.target.closest('[data-f]');if(!el)return;let v=el.type==='checkbox'?el.checked:el.value;if(el.type==='number')v=Number(v);patch('textFormat',el.dataset.f,v);};}
 if(currentTab==='rules'){const r=effectiveRules(t),z=effectiveSizing(t),s=styleData(t),b=renderBounds(s),fallbackAspect=Math.max(.1,(b.w*9)/(b.h*5.2)),rawUiMode=z.mode||s.textSizing&&s.textSizing.mode||'',storedUiAspect=Number(z.aspect||s.textSizing&&s.textSizing.aspect),aspect=rawUiMode==='auto'?fallbackAspect:(storedUiAspect>0?storedUiAspect:fallbackAspect);q('[data-page="rules"]').innerHTML=`<div class="ts-section"><h4>尺寸策略</h4><label class="ts-row"><span>尺寸策略</span><select data-z="mode"><option value="uniform">固定长宽比</option><option value="stretch">自由拉伸</option></select></label><label class="ts-row" data-aspect-row><span>长宽比</span><input data-z="aspect" type="number" min="0.1" max="20" step="0.01" value="${Math.round(aspect*100)/100}"></label><p class="ts-hint">文字会先使用画出的文字区域；只有放不下时，文本框和全部图层才一起扩大。</p></div><div class="ts-section"><h4>输入限制</h4><label class="ts-row"><span>最多字符</span><input data-r="maxLength" type="number" min="0" max="10000" value="${r.maxLength||0}" placeholder="0=不限"></label><label class="ts-row"><span>允许类型</span><select data-r="type"><option value="any">任意文字</option><option value="number">仅数字</option><option value="letter">仅字母</option><option value="chinese">仅中文</option><option value="alnum">数字和字母</option><option value="regex">自定义正则</option></select></label><label class="ts-row"><span>自定义正则</span><input data-r="pattern" value="${esc(r.pattern||'')}" placeholder="例如 ^[A-Z0-9]*$"></label><label class="ts-row"><span>空值</span><select data-r="required"><option value="false">允许为空</option><option value="true">不允许为空</option></select></label><p class="ts-hint">限制会在输入时即时生效。正则填写错误时自动按“任意文字”处理。</p></div>`;const p=q('[data-page="rules"]'),modeSelect=p.querySelector('[data-z="mode"]'),syncModeUi=()=>{p.querySelector('[data-aspect-row]').hidden=modeSelect.value!=='uniform';};modeSelect.value=sizingMode(z.mode);p.querySelector('[data-r="type"]').value=r.type||'any';p.querySelector('[data-r="required"]').value=String(!!r.required);syncModeUi();p.onchange=e=>{let el=e.target.closest('[data-z],[data-r]');if(!el)return;let v=el.type==='number'?Number(el.value):el.value;if(el.dataset.r==='required')v=v==='true';patch(el.dataset.z?'textSizing':'textRules',el.dataset.z||el.dataset.r,v);if(el.dataset.z==='mode')syncModeUi();};}
 q('.ts-status').textContent=selected().length?`已选中 ${selected().length} 个文本框`:'请选择文本框';}
function allowed(text,r){if(!r)return true;if(Number(r.maxLength)>0&&Array.from(text).length>Number(r.maxLength))return false;if(r.type==='number'&&!/^\d*$/.test(text))return false;if(r.type==='letter'&&!/^[A-Za-z]*$/.test(text))return false;if(r.type==='chinese'&&!/^[\u3400-\u9fff]*$/.test(text))return false;if(r.type==='alnum'&&!/^[A-Za-z0-9]*$/.test(text))return false;if(r.type==='regex'&&r.pattern){try{if(!(new RegExp(r.pattern)).test(text))return false;}catch(_){}}return true;}
function textSelection(inner){const cur=inner.textContent||'',sel=getSelection();if(!sel||!sel.rangeCount)return{cur,start:cur.length,end:cur.length};const range=sel.getRangeAt(0);if(!inner.contains(range.startContainer)||!inner.contains(range.endContainer))return{cur,start:cur.length,end:cur.length};try{const head=document.createRange();head.selectNodeContents(inner);head.setEnd(range.startContainer,range.startOffset);const start=head.toString().length;return{cur,start,end:start+range.toString().length};}catch(_){return{cur,start:cur.length,end:cur.length};}}
function proposedText(inner,inserted){const x=textSelection(inner);return x.cur.slice(0,x.start)+String(inserted==null?'':inserted)+x.cur.slice(x.end);}
function rejectInput(inner){inner.animate([{background:'#ffd8d8'},{background:''}],{duration:240});}
document.addEventListener('beforeinput',e=>{const inner=e.target.closest&&e.target.closest('.card-inner[contenteditable="true"]'),id=editing;if(!inner||!id||!TB[id])return;const r=effectiveRules(TB[id]);if(e.inputType&&e.inputType.startsWith('delete'))return;if(e.inputType==='insertFromPaste'&&e.data==null)return;const inserted=e.inputType==='insertParagraph'||e.inputType==='insertLineBreak'?'\n':e.data||'';if(!allowed(proposedText(inner,inserted),r)){e.preventDefault();rejectInput(inner);}},true);
document.addEventListener('paste',e=>{const inner=e.target.closest&&e.target.closest('.card-inner[contenteditable="true"]'),id=editing;if(!inner||!id||!TB[id])return;const text=e.clipboardData&&e.clipboardData.getData('text/plain')||'';if(!allowed(proposedText(inner,text),effectiveRules(TB[id]))){e.preventDefault();e.stopImmediatePropagation();rejectInput(inner);}},true);
let editFitFrame=0,pendingFitId=null;
function scheduleEditingFit(id){pendingFitId=id;if(editFitFrame)return;editFitFrame=requestAnimationFrame(()=>{editFitFrame=0;const current=pendingFitId;pendingFitId=null;if(current&&editing===current&&TB[current]&&els[current]){window.applyTextStyleToNode(current);layout();}});}
document.addEventListener('input',e=>{const inner=e.target.closest&&e.target.closest('.card-inner[contenteditable="true"]'),id=editing;if(!inner||!id||!TB[id])return;const value=inner.textContent||'',r=effectiveRules(TB[id]),deleting=e.inputType&&e.inputType.startsWith('delete');if(!deleting&&!allowed(value,r)){inner.textContent=inner._tsLastAccepted==null?(TB[id].text||''):inner._tsLastAccepted;const range=document.createRange();range.selectNodeContents(inner);range.collapse(false);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);rejectInput(inner);}else inner._tsLastAccepted=value;scheduleEditingFit(id);},true);
async function loadExternal(){try{let r;if(window.api&&api.loadTextStyles)r=await api.loadTextStyles();else{const x=localStorage.getItem('bmap.textStyles');r=x?JSON.parse(x):null;}if(r&&Array.isArray(r.styles)){customStyles=r.styles.filter(x=>x&&x.id);defaultStyleId=r.defaultStyleId||'classic';styleSettings=r.styleSettings||{};externalPath=r.path||'';rebuildStyles();applyAll();if(q('#textStylePanel'))refresh();}}catch(_){} }
function init(){shell();loadSystemFonts();const btn=q('#textStyleBtn');if(btn)btn.onclick=e=>{e.stopPropagation();open('styles');};if(!window.__textRulesCommitWrapped){window.__textRulesCommitWrapped=true;const baseStart=startEdit,baseCommit=commitEdit;startEdit=function(id){baseStart(id);const inner=els[id]&&els[id]._inner;if(editing===id&&inner)inner._tsLastAccepted=inner.textContent||'';};commitEdit=function(id){const t=TB[id],inner=els[id]&&els[id]._inner;if(t&&inner){const r=effectiveRules(t),value=inner.textContent||'';if((r.required&&!value.trim())||!allowed(value,r)){inner.textContent=t.text||'';rejectInput(inner);}}return baseCommit(id);};}if(window.api&&api.onTextStylesChanged)api.onTextStylesChanged(()=>loadExternal());loadExternal();}
window.TextStyleFeature={open,close,refresh,loadExternal,BUILTINS,getDefaultStyleId:()=>defaultStyleId,createAtStructuralNode:ref=>window.createStructuralNodeTextbox&&window.createStructuralNodeTextbox(ref,defaultStyleId,true),openForNode:id=>{if(TB[id])selectTb(id);open('styles',TB[id]._nodeAttach?'node':'normal');},applyStyleToAll:id=>applyStyleToAll(getStyle(id)),placeStyleOnAllNodes:id=>placeStyleOnAllNodes(getStyle(id))};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
